# Site settings
title: "Adam's Lists"
email: ajkochanowicz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "I don't blog. I write carefully-collected lists."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamslists.com" # the base hostname & protocol for your site
twitter_username: ajkochanowicz
github_username:  ajkochanowicz

# Build settings
markdown: kramdown

gems:
  - "autoprefixer-rails"
  - "jekyll-assets"

sass:
  load_paths:
    - "_sass"
    - "kickstart"
    - "kickstart/lib-core/sass"
assets:
  sources:
    - "_assets/javascripts"
    - "_assets/stylesheets"
    - "_sass"
    - "kickstart"
    - "kickstart/lib-core/sass"
